const PREV = 'USER-'
export const SET_PORTRAIT_URL = `${PREV}SET_PORTRAIT_URL`
export const FETCH_LOGIN_USER = `${PREV}FETCH_LOGIN_USER`
export const FETCH_BASIC_INFO = `${PREV}FETCH_BASIC_INFO`
export const FETCH_ORGANIZATIONAL_INFO = `${PREV}FETCH_ORGANIZATIONAL_INFO`
export const FETCH_ASSET_INFO = `${PREV}FETCH_ASSET_INFO`
export const FETCH_WORK_RECORDS = `${PREV}FETCH_WORK_RECORDS`
export const FETCH_FAMILY_MEMBERS = `${PREV}FETCH_FAMILY_MEMBER`
